# Generated by Django 4.1.3 on 2024-02-29 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="appointments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("department", models.CharField(max_length=100)),
                ("message", models.CharField(max_length=200)),
                ("doctor", models.CharField(max_length=100)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departmentname", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("insurance_no", models.IntegerField()),
                ("phone", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="pharmacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pharmacynamme", models.CharField(max_length=50)),
                ("pharmacyaddress", models.CharField(max_length=100)),
                ("pharmacyphone", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stafffname", models.CharField(max_length=100)),
                ("stafflname", models.CharField(max_length=100)),
                ("staffaddress", models.CharField(max_length=100)),
                ("staffphone", models.CharField(max_length=20)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainSystem.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admissiondate", models.DateTimeField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainSystem.patient",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainSystem.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medication", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
                ("cost", models.IntegerField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainSystem.patient",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="patient",
            name="pharmacy",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainSystem.pharmacy",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("servicedescription", models.CharField(max_length=100)),
                ("cost", models.IntegerField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainSystem.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctorfname", models.CharField(max_length=100)),
                ("doctorlname", models.CharField(max_length=100)),
                ("doctorphone", models.CharField(max_length=20)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainSystem.department",
                    ),
                ),
            ],
        ),
    ]
